package com.myself.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class EventActionDefaultConfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public EventActionDefaultConfExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNodetypeIsNull() {
            addCriterion("NodeType is null");
            return (Criteria) this;
        }

        public Criteria andNodetypeIsNotNull() {
            addCriterion("NodeType is not null");
            return (Criteria) this;
        }

        public Criteria andNodetypeEqualTo(Byte value) {
            addCriterion("NodeType =", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeNotEqualTo(Byte value) {
            addCriterion("NodeType <>", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeGreaterThan(Byte value) {
            addCriterion("NodeType >", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("NodeType >=", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeLessThan(Byte value) {
            addCriterion("NodeType <", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeLessThanOrEqualTo(Byte value) {
            addCriterion("NodeType <=", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeIn(List<Byte> values) {
            addCriterion("NodeType in", values, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeNotIn(List<Byte> values) {
            addCriterion("NodeType not in", values, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeBetween(Byte value1, Byte value2) {
            addCriterion("NodeType between", value1, value2, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeNotBetween(Byte value1, Byte value2) {
            addCriterion("NodeType not between", value1, value2, "nodetype");
            return (Criteria) this;
        }

        public Criteria andEventnameIsNull() {
            addCriterion("EventName is null");
            return (Criteria) this;
        }

        public Criteria andEventnameIsNotNull() {
            addCriterion("EventName is not null");
            return (Criteria) this;
        }

        public Criteria andEventnameEqualTo(String value) {
            addCriterion("EventName =", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotEqualTo(String value) {
            addCriterion("EventName <>", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameGreaterThan(String value) {
            addCriterion("EventName >", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameGreaterThanOrEqualTo(String value) {
            addCriterion("EventName >=", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameLessThan(String value) {
            addCriterion("EventName <", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameLessThanOrEqualTo(String value) {
            addCriterion("EventName <=", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameLike(String value) {
            addCriterion("EventName like", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotLike(String value) {
            addCriterion("EventName not like", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameIn(List<String> values) {
            addCriterion("EventName in", values, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotIn(List<String> values) {
            addCriterion("EventName not in", values, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameBetween(String value1, String value2) {
            addCriterion("EventName between", value1, value2, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotBetween(String value1, String value2) {
            addCriterion("EventName not between", value1, value2, "eventname");
            return (Criteria) this;
        }

        public Criteria andActiontypeIsNull() {
            addCriterion("ActionType is null");
            return (Criteria) this;
        }

        public Criteria andActiontypeIsNotNull() {
            addCriterion("ActionType is not null");
            return (Criteria) this;
        }

        public Criteria andActiontypeEqualTo(String value) {
            addCriterion("ActionType =", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotEqualTo(String value) {
            addCriterion("ActionType <>", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeGreaterThan(String value) {
            addCriterion("ActionType >", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeGreaterThanOrEqualTo(String value) {
            addCriterion("ActionType >=", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeLessThan(String value) {
            addCriterion("ActionType <", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeLessThanOrEqualTo(String value) {
            addCriterion("ActionType <=", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeLike(String value) {
            addCriterion("ActionType like", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotLike(String value) {
            addCriterion("ActionType not like", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeIn(List<String> values) {
            addCriterion("ActionType in", values, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotIn(List<String> values) {
            addCriterion("ActionType not in", values, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeBetween(String value1, String value2) {
            addCriterion("ActionType between", value1, value2, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotBetween(String value1, String value2) {
            addCriterion("ActionType not between", value1, value2, "actiontype");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("Priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("Priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("Priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("Priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("Priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("Priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("Priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("Priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("Priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("Priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("Priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("Priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andFailpolicyIsNull() {
            addCriterion("FailPolicy is null");
            return (Criteria) this;
        }

        public Criteria andFailpolicyIsNotNull() {
            addCriterion("FailPolicy is not null");
            return (Criteria) this;
        }

        public Criteria andFailpolicyEqualTo(Byte value) {
            addCriterion("FailPolicy =", value, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyNotEqualTo(Byte value) {
            addCriterion("FailPolicy <>", value, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyGreaterThan(Byte value) {
            addCriterion("FailPolicy >", value, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyGreaterThanOrEqualTo(Byte value) {
            addCriterion("FailPolicy >=", value, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyLessThan(Byte value) {
            addCriterion("FailPolicy <", value, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyLessThanOrEqualTo(Byte value) {
            addCriterion("FailPolicy <=", value, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyIn(List<Byte> values) {
            addCriterion("FailPolicy in", values, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyNotIn(List<Byte> values) {
            addCriterion("FailPolicy not in", values, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyBetween(Byte value1, Byte value2) {
            addCriterion("FailPolicy between", value1, value2, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andFailpolicyNotBetween(Byte value1, Byte value2) {
            addCriterion("FailPolicy not between", value1, value2, "failpolicy");
            return (Criteria) this;
        }

        public Criteria andDimensionIsNull() {
            addCriterion("Dimension is null");
            return (Criteria) this;
        }

        public Criteria andDimensionIsNotNull() {
            addCriterion("Dimension is not null");
            return (Criteria) this;
        }

        public Criteria andDimensionEqualTo(Byte value) {
            addCriterion("Dimension =", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotEqualTo(Byte value) {
            addCriterion("Dimension <>", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionGreaterThan(Byte value) {
            addCriterion("Dimension >", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionGreaterThanOrEqualTo(Byte value) {
            addCriterion("Dimension >=", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionLessThan(Byte value) {
            addCriterion("Dimension <", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionLessThanOrEqualTo(Byte value) {
            addCriterion("Dimension <=", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionIn(List<Byte> values) {
            addCriterion("Dimension in", values, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotIn(List<Byte> values) {
            addCriterion("Dimension not in", values, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionBetween(Byte value1, Byte value2) {
            addCriterion("Dimension between", value1, value2, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotBetween(Byte value1, Byte value2) {
            addCriterion("Dimension not between", value1, value2, "dimension");
            return (Criteria) this;
        }

        public Criteria andEditableIsNull() {
            addCriterion("Editable is null");
            return (Criteria) this;
        }

        public Criteria andEditableIsNotNull() {
            addCriterion("Editable is not null");
            return (Criteria) this;
        }

        public Criteria andEditableEqualTo(Byte value) {
            addCriterion("Editable =", value, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableNotEqualTo(Byte value) {
            addCriterion("Editable <>", value, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableGreaterThan(Byte value) {
            addCriterion("Editable >", value, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableGreaterThanOrEqualTo(Byte value) {
            addCriterion("Editable >=", value, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableLessThan(Byte value) {
            addCriterion("Editable <", value, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableLessThanOrEqualTo(Byte value) {
            addCriterion("Editable <=", value, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableIn(List<Byte> values) {
            addCriterion("Editable in", values, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableNotIn(List<Byte> values) {
            addCriterion("Editable not in", values, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableBetween(Byte value1, Byte value2) {
            addCriterion("Editable between", value1, value2, "editable");
            return (Criteria) this;
        }

        public Criteria andEditableNotBetween(Byte value1, Byte value2) {
            addCriterion("Editable not between", value1, value2, "editable");
            return (Criteria) this;
        }

        public Criteria andDescripitionIsNull() {
            addCriterion("Descripition is null");
            return (Criteria) this;
        }

        public Criteria andDescripitionIsNotNull() {
            addCriterion("Descripition is not null");
            return (Criteria) this;
        }

        public Criteria andDescripitionEqualTo(String value) {
            addCriterion("Descripition =", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionNotEqualTo(String value) {
            addCriterion("Descripition <>", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionGreaterThan(String value) {
            addCriterion("Descripition >", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionGreaterThanOrEqualTo(String value) {
            addCriterion("Descripition >=", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionLessThan(String value) {
            addCriterion("Descripition <", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionLessThanOrEqualTo(String value) {
            addCriterion("Descripition <=", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionLike(String value) {
            addCriterion("Descripition like", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionNotLike(String value) {
            addCriterion("Descripition not like", value, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionIn(List<String> values) {
            addCriterion("Descripition in", values, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionNotIn(List<String> values) {
            addCriterion("Descripition not in", values, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionBetween(String value1, String value2) {
            addCriterion("Descripition between", value1, value2, "descripition");
            return (Criteria) this;
        }

        public Criteria andDescripitionNotBetween(String value1, String value2) {
            addCriterion("Descripition not between", value1, value2, "descripition");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Long value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Long value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Long value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Long value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Long value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Long> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Long> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Long value1, Long value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Long value1, Long value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Long value) {
            addCriterion("UpdateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Long value) {
            addCriterion("UpdateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Long value) {
            addCriterion("UpdateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UpdateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Long value) {
            addCriterion("UpdateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Long value) {
            addCriterion("UpdateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Long> values) {
            addCriterion("UpdateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Long> values) {
            addCriterion("UpdateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Long value1, Long value2) {
            addCriterion("UpdateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Long value1, Long value2) {
            addCriterion("UpdateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}