package com.myself.mybatis.entity;

public class EventActionDefaultConf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.NodeType
     *
     * @mbg.generated
     */
    private Byte nodetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.EventName
     *
     * @mbg.generated
     */
    private String eventname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.ActionType
     *
     * @mbg.generated
     */
    private String actiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.FailPolicy
     *
     * @mbg.generated
     */
    private Byte failpolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Dimension
     *
     * @mbg.generated
     */
    private Byte dimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Editable
     *
     * @mbg.generated
     */
    private Byte editable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Descripition
     *
     * @mbg.generated
     */
    private String descripition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.CreateTime
     *
     * @mbg.generated
     */
    private Long createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.UpdateTime
     *
     * @mbg.generated
     */
    private Long updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Id
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Id
     *
     * @param id the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.NodeType
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.NodeType
     *
     * @mbg.generated
     */
    public Byte getNodetype() {
        return nodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.NodeType
     *
     * @param nodetype the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.NodeType
     *
     * @mbg.generated
     */
    public void setNodetype(Byte nodetype) {
        this.nodetype = nodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.EventName
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.EventName
     *
     * @mbg.generated
     */
    public String getEventname() {
        return eventname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.EventName
     *
     * @param eventname the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.EventName
     *
     * @mbg.generated
     */
    public void setEventname(String eventname) {
        this.eventname = eventname == null ? null : eventname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.ActionType
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.ActionType
     *
     * @mbg.generated
     */
    public String getActiontype() {
        return actiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.ActionType
     *
     * @param actiontype the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.ActionType
     *
     * @mbg.generated
     */
    public void setActiontype(String actiontype) {
        this.actiontype = actiontype == null ? null : actiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Priority
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Priority
     *
     * @param priority the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.FailPolicy
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.FailPolicy
     *
     * @mbg.generated
     */
    public Byte getFailpolicy() {
        return failpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.FailPolicy
     *
     * @param failpolicy the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.FailPolicy
     *
     * @mbg.generated
     */
    public void setFailpolicy(Byte failpolicy) {
        this.failpolicy = failpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Dimension
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Dimension
     *
     * @mbg.generated
     */
    public Byte getDimension() {
        return dimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Dimension
     *
     * @param dimension the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Dimension
     *
     * @mbg.generated
     */
    public void setDimension(Byte dimension) {
        this.dimension = dimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Editable
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Editable
     *
     * @mbg.generated
     */
    public Byte getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Editable
     *
     * @param editable the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Editable
     *
     * @mbg.generated
     */
    public void setEditable(Byte editable) {
        this.editable = editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Descripition
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Descripition
     *
     * @mbg.generated
     */
    public String getDescripition() {
        return descripition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Descripition
     *
     * @param descripition the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.Descripition
     *
     * @mbg.generated
     */
    public void setDescripition(String descripition) {
        this.descripition = descripition == null ? null : descripition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.CreateTime
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.CreateTime
     *
     * @mbg.generated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.CreateTime
     *
     * @param createtime the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.UpdateTime
     *
     * @return the value of TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.UpdateTime
     *
     * @mbg.generated
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.UpdateTime
     *
     * @param updatetime the value for TB_YX_FLOWX_EVENT_ACTION_DEFAULT_CONF.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }
}